### PR TITLE
Fix for 0.4

### PR DESCRIPTION
**Pull request by yuyichao**
* Remove pre 0.3 support
* Fix 0.4 deprecation warnings
* Upgrade travis settings

Some of the functions should probably be deprecated but I don't want to decide that.

Close: https://github.com/lindahua/NumericFuns.jl/issues/2

### CODE REVIEW

**Comment by yuyichao** [comment]
Finally got all the tests to pass on the master, hopefully I fixed all the changes for 0.3 as well....

**Comment by yuyichao** [comment]
:beers: All tests passed on CI for both 0.3 and 0.4 (also master).

**Comment by yuyichao** [comment]
@lindahua In the off chance that you also have issue getting notifications from your own repo....

**Comment by yuyichao** [comment]
Ping @lindahua

**Comment by yuyichao** [comment]
Ping @lindahua

**Comment by lindahua** [comment]
Sorry for the delay, thanks for working on this.

**Comment by hayd** [comment]
Does this also fix #3 ?

**Comment by yuyichao** [comment]
@hayd No. But it should be fixed by #6 (if it passes tests on 0.3....)

**Pull request merged**
